#
# Makefile for restlet server
#

include $(POCO_BASE)/build/rules/global

objects = RestServer
target = rest_server
target_libs=PocoUtil PocoFoundation PocoNet

include $(POCO_BASE)/build/rules/exec
